services:
  - type: web
    name: grib-inreach-service
    runtime: python
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.browsers
      - key: PORT
        value: "10000"
