services:
  - type: web
    name: grib-inreach-service
    runtime: python
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/.browsers
