services:
  - type: web
    name: grib-inreach-service
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/src/browsers
